title:        Select Languages
description:  Choose your language based on letters and characters.
url:          http://a.hoff.in

version:      0.0.0

author:
  name:       'John Hoffer'
  email:      'john@hoff.in'
markdown:     kramdown
permalink:    pretty
pygments:     true
highlighter:  rouge

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md",".DS_Store"]

image : http://commons.wikimedia.org/wiki/File:Language_icon.svg
imagesecure : https://commons.wikimedia.org/wiki/File:Language_icon.svg

# Footer
footer_title: Hoff in
footer_link: http://a.hoff.in
footer_image_source: https://en.wikipedia.org/wiki/Tigris#/media/File:B124ellst.png
footer_image_width: 60
